# Generated by Django 4.1.5 on 2023-03-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
