# Generated by Django 4.1.5 on 2023-03-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0004_delete_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id_project', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=5000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
