# Generated by Django 4.1.5 on 2023-03-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='status',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='title',
        ),
    ]
