# Generated by Django 4.1.5 on 2023-03-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_projects_status_remove_projects_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
