# Generated by Django 4.1.5 on 2023-03-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_projects_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
