# Generated by Django 4.1.5 on 2023-03-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
