# Generated by Django 4.1.5 on 2023-03-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0024_delete_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_project', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
    ]
