# Generated by Django 4.1.5 on 2023-03-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_projects_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='department',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='main_languare',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
