# Generated by Django 4.1.5 on 2023-03-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_projects_department_projects_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
