# Generated by Django 4.1.5 on 2023-03-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0030_delete_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_project', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('main_languare', models.CharField(blank=True, max_length=6, null=True)),
                ('total_funding_amount', models.CharField(max_length=10, null=True)),
                ('currency', models.CharField(max_length=60, null=True)),
                ('comntact_email', models.CharField(max_length=60, null=True)),
                ('contact_phone', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
