# Generated by Django 4.1.5 on 2023-04-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_remove_projects_academic_discipline1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='academic_discipline1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='academic_discipline2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='academic_discipline3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='academic_discipline4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='academic_discipline5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='contact_email',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='contact_phone',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='coordinating_institution',
            field=models.CharField(max_length=50, null='NTNU'),
            preserve_default='NTNU',
        ),
        migrations.AddField(
            model_name='projects',
            name='currency',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='department',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='funding1',
            field=models.CharField(max_length=50, null='None'),
            preserve_default='None',
        ),
        migrations.AddField(
            model_name='projects',
            name='funding2',
            field=models.CharField(max_length=50, null='None'),
            preserve_default='None',
        ),
        migrations.AddField(
            model_name='projects',
            name='funding3',
            field=models.CharField(max_length=50, null='None'),
            preserve_default='None',
        ),
        migrations.AddField(
            model_name='projects',
            name='funding4',
            field=models.CharField(max_length=50, null='None'),
            preserve_default='None',
        ),
        migrations.AddField(
            model_name='projects',
            name='funding5',
            field=models.CharField(max_length=50, null='None'),
            preserve_default='None',
        ),
        migrations.AddField(
            model_name='projects',
            name='keyword1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='keyword2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='keyword3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='keyword4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='keyword5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='main_language',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='manager_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant10_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant10_surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant1_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant1_surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant2_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant2_surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant3_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant3_surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant4_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant4_surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant5_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant5_surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant6_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant6_surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant7_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant7_surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant8_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant8_surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant9_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='participant9_surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_category1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_category2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_category3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_category4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_category5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='publishable',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='published',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='summary',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='total_funding_amount',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
