# Generated by Django 4.1.5 on 2023-04-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_projects_academic_discipline1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
