# Generated by Django 4.1.5 on 2023-04-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
